export type Facility = {
  id: string;
  slug: string;
  facilityNumber: string;
  name: string;
  city: string;
  county: string;
  capacity: number;
  ccldLink: string;
  status: "active" | "inactive";
  rebuttalsCount: number;
  lastUpdated: string;
};

export const MOCK_FACILITIES: Facility[] = [
  {
    id: "fac-001",
    slug: "sunny-days-care-home",
    facilityNumber: "374603921",
    name: "Sunny Days Care Home",
    city: "San Diego",
    county: "San Diego",
    capacity: 6,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/374603921",
    status: "active",
    rebuttalsCount: 2,
    lastUpdated: "2026-05-12",
  },
  {
    id: "fac-002",
    slug: "oak-tree-senior-living",
    facilityNumber: "193608274",
    name: "Oak Tree Senior Living",
    city: "Pasadena",
    county: "Los Angeles",
    capacity: 45,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/193608274",
    status: "active",
    rebuttalsCount: 0,
    lastUpdated: "2026-06-01",
  },
  {
    id: "fac-003",
    slug: "bayside-residential-care",
    facilityNumber: "015600293",
    name: "Bayside Residential Care",
    city: "Oakland",
    county: "Alameda",
    capacity: 15,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/015600293",
    status: "active",
    rebuttalsCount: 5,
    lastUpdated: "2026-04-20",
  },
  {
    id: "fac-004",
    slug: "whispering-pines-retreat",
    facilityNumber: "317002845",
    name: "Whispering Pines Retreat",
    city: "Auburn",
    county: "Placer",
    capacity: 6,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/317002845",
    status: "active",
    rebuttalsCount: 1,
    lastUpdated: "2026-03-15",
  },
  {
    id: "fac-005",
    slug: "golden-years-assisted-living",
    facilityNumber: "306001837",
    name: "Golden Years Assisted Living",
    city: "Irvine",
    county: "Orange",
    capacity: 120,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/306001837",
    status: "active",
    rebuttalsCount: 12,
    lastUpdated: "2026-06-02",
  },
  {
    id: "fac-006",
    slug: "valley-view-manor",
    facilityNumber: "107204892",
    name: "Valley View Manor",
    city: "Fresno",
    county: "Fresno",
    capacity: 30,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/107204892",
    status: "inactive",
    rebuttalsCount: 0,
    lastUpdated: "2025-11-10",
  },
  {
    id: "fac-007",
    slug: "coastal-breeze-care",
    facilityNumber: "426802194",
    name: "Coastal Breeze Care",
    city: "Santa Barbara",
    county: "Santa Barbara",
    capacity: 6,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/426802194",
    status: "active",
    rebuttalsCount: 0,
    lastUpdated: "2026-05-25",
  },
  {
    id: "fac-008",
    slug: "rose-garden-villa",
    facilityNumber: "435201984",
    name: "Rose Garden Villa",
    city: "San Jose",
    county: "Santa Clara",
    capacity: 8,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/435201984",
    status: "active",
    rebuttalsCount: 3,
    lastUpdated: "2026-04-05",
  },
  {
    id: "fac-009",
    slug: "desert-oasis-senior-care",
    facilityNumber: "336402758",
    name: "Desert Oasis Senior Care",
    city: "Palm Springs",
    county: "Riverside",
    capacity: 12,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/336402758",
    status: "active",
    rebuttalsCount: 1,
    lastUpdated: "2026-02-18",
  },
  {
    id: "fac-010",
    slug: "mountain-view-lodge",
    facilityNumber: "365801947",
    name: "Mountain View Lodge",
    city: "San Bernardino",
    county: "San Bernardino",
    capacity: 25,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/365801947",
    status: "active",
    rebuttalsCount: 4,
    lastUpdated: "2026-05-30",
  },
  {
    id: "fac-011",
    slug: "pacific-heights-care",
    facilityNumber: "385600281",
    name: "Pacific Heights Care",
    city: "San Francisco",
    county: "San Francisco",
    capacity: 40,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/385600281",
    status: "active",
    rebuttalsCount: 2,
    lastUpdated: "2026-06-03",
  },
  {
    id: "fac-012",
    slug: "serenity-house",
    facilityNumber: "347001928",
    name: "Serenity House",
    city: "Sacramento",
    county: "Sacramento",
    capacity: 6,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/347001928",
    status: "active",
    rebuttalsCount: 0,
    lastUpdated: "2026-01-12",
  },
  {
    id: "fac-013",
    slug: "maple-grove-memory-care",
    facilityNumber: "075602938",
    name: "Maple Grove Memory Care",
    city: "Walnut Creek",
    county: "Contra Costa",
    capacity: 65,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/075602938",
    status: "active",
    rebuttalsCount: 7,
    lastUpdated: "2026-05-22",
  },
  {
    id: "fac-014",
    slug: "harmony-hills",
    facilityNumber: "565802837",
    name: "Harmony Hills",
    city: "Thousand Oaks",
    county: "Ventura",
    capacity: 14,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/565802837",
    status: "inactive",
    rebuttalsCount: 1,
    lastUpdated: "2025-08-30",
  },
  {
    id: "fac-015",
    slug: "carmel-valley-estates",
    facilityNumber: "275201948",
    name: "Carmel Valley Estates",
    city: "Carmel",
    county: "Monterey",
    capacity: 6,
    ccldLink: "https://www.ccld.dss.ca.gov/carefacilitysearch/FacDetail/275201948",
    status: "active",
    rebuttalsCount: 0,
    lastUpdated: "2026-04-11",
  }
];
