version: '3.8'

services:
  db:
    image: postgres:15
    container_name: carehomes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ADMIN321
      POSTGRES_DB: carehomes
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: carehomes-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:ADMIN321@db:5432/carehomes

volumes:
  db_data: